# Generated automatically by `monai.apps.auto3dseg.bundle_gen`
# For more information please visit: https://docs.monai.io/

# source file: ./workdir/algorithm_templates/segresnet2d/configs/network.yaml
# source file: ./workdir/algorithm_templates/segresnet2d/configs/transforms_validate.yaml
# source file: ./workdir/algorithm_templates/segresnet2d/configs/transforms_infer.yaml
# source file: ./workdir/algorithm_templates/segresnet2d/configs/hyper_parameters.yaml
# source file: ./workdir/algorithm_templates/segresnet2d/configs/transforms_train.yaml


_meta_: {}
amp: true
bundle_root: ./workdir/segresnet2d_0
ckpt_path: $@bundle_root + '/model_fold' + str(@fold)
data_file_base_dir: /workspace/data/msd/Task05_Prostate
data_list_file_path: /workspace/MONAI/auto3dseg/Task05_Prostate_v2_20220908/msd_task05_prostate_folds.json
determ: false
finetune: {activate: false, pretrained_ckpt_name: $@bundle_root + '/model_fold' +
    str(@fold) + '/best_metric_model.pt'}
fold: 0
image_key: image
infer: {ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt',
  data_list_key: testing, fast: false, ouptut_path: $@bundle_root + '/prediction_'
    + @infer#data_list_key}
input_channels: 2
label_key: label
learning_rate: 0.025
loss: {_target_: DiceFocalLoss, batch: true, include_background: true, sigmoid: $not
    @softmax, smooth_dr: 1.0e-05, smooth_nr: 1.0e-05, softmax: $@softmax, squared_pred: true,
  to_onehot_y: $@softmax}
lr_scheduler: {_target_: torch.optim.lr_scheduler.StepLR, gamma: 0.5, optimizer: $@optimizer,
  step_size: $@num_iterations // 5}
num_adjacent_slices: 1
num_images_per_batch: 2
num_iterations: 40000
num_iterations_per_validation: 500
num_patches_per_image: 1
num_sw_batch_size: 2
optimizer: {_target_: torch.optim.SGD, lr: '@learning_rate', momentum: 0.9, weight_decay: 4.0e-05}
output_classes: 3
overlap_ratio: 0.625
patch_size: [320, 320, $@num_adjacent_slices * 2 + 1]
patch_size_valid: [320, 320, $@num_adjacent_slices * 2 + 1]
softmax: true
validate: {ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt',
  ouptut_path: $@bundle_root + '/prediction_fold' + str(@fold), save_mask: true}
