default_language_version:
  python: python3.8

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: quarterly
  # submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: detect-private-key

  #- repo: https://github.com/asottile/pyupgrade
  #  rev: v2.23.2
  #  hooks:
  #    - id: pyupgrade
  #      args: [--py36-plus]
  #      name: Upgrade code

  #- repo: https://github.com/asottile/yesqa
  #  rev: v1.2.3
  #  hooks:
  #    - id: yesqa
  #      name: Unused noqa

  #- repo: https://github.com/PyCQA/isort
  #  rev: 5.9.3
  #  hooks:
  #    - id: isort
  #      name: Format imports

  # - repo: https://github.com/psf/black
  #   rev: 21.7b0
  #   hooks:
  #     - id: black
  #       name: Format code

  #- repo: https://github.com/executablebooks/mdformat
  #  rev: 0.7.8
  #  hooks:
  #    - id: mdformat
  #      additional_dependencies:
  #        - mdformat-gfm
  #        - mdformat_frontmatter
  #      exclude: CHANGELOG.md

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
  #       name: Check PEP8
