network:
  _target_: UNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  norm: batch
inferer:
  _target_: SlidingWindowInferer
  roi_size: [96, 96, 96]
  sw_batch_size: 4
  overlap: 0.5
