---
bundle_root: null

training:
  # hyper-parameters
  amp: true
  bundle_root: null
  ckpt_path: "$@bundle_root + '/model_fold' + str(@training#fold)"
  data_file_base_dir: null
  data_list_file_path: null
  determ: false
  fold: 0
  input_channels: null
  learning_rate: 0.2
  num_images_per_batch: 2
  num_iterations: 40000
  num_iterations_per_validation: 500
  num_patches_per_image: 1
  num_sw_batch_size: 2
  output_classes: null
  overlap_ratio: 0.625
  patch_size: null
  patch_size_valid: null
  softmax: true

  loss:
    _target_: DiceFocalLoss
    include_background: true
    to_onehot_y: "$@training#softmax"
    softmax: "$@training#softmax"
    sigmoid: "$not @training#softmax"
    squared_pred: true
    batch: true
    smooth_nr: 1.0e-05
    smooth_dr: 1.0e-05
  optimizer:
    _target_: torch.optim.SGD
    lr: "@training#learning_rate"
    momentum: 0.9
    weight_decay: 4.0e-05
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    optimizer: "$@training#optimizer"
    step_size: "$@training#num_iterations // 5"
    gamma: 0.5

# fine-tuning
finetune:
  activate: false
  pretrained_ckpt_name: "$@bundle_root + '/model_fold' + str(@training#fold) + '/best_metric_model.pt'"

# validation
validate:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@training#fold) + '/best_metric_model.pt'"
  save_mask: true
  ouptut_path: "$@bundle_root + '/prediction_fold' + str(@training#fold)"

# inference
infer:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@training#fold) + '/best_metric_model.pt'"
  fast: false
  data_list_key: testing
  ouptut_path: "$@bundle_root + '/prediction_' + @training#infer#data_list_key"
