---
training:
  network:
    _target_: UNet
    spatial_dims: 3
    in_channels: "@training#input_channels"
    out_channels: "@training#output_classes"
    channels: [32, 64, 128, 256, 512]
    strides: [2, 2, 2, 2]
    kernel_size: 3
    up_kernel_size: 3
    num_res_units: 2
    act: PRELU
    norm: BATCH
    dropout: 0.2
    bias: true
    dimensions:
