---
image_key: image
label_key: label
transforms_validate:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: ["@image_key", "@label_key"]
  - _target_: EnsureChannelFirstd
    keys: ["@image_key", "@label_key"]
  - _target_: Orientationd
    keys: ["@image_key", "@label_key"]
    axcodes: RAS
  - _target_: Spacingd
    keys: ["@image_key", "@label_key"]
    pixdim: null
    mode: [bilinear, nearest]
    align_corners: [true, true]
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - PLACEHOLDER_INTENSITY_NORMALIZATION
  - _target_: CastToTyped
    keys: ["@image_key", "@label_key"]
    dtype: ["$torch.float32", "$torch.uint8"]
