amp: true
bundle_root: /RW/2022/auto3dseg/btcv_testrun/auto3dseg/monai/apps/auto3dseg/algo_teamplates/SwinUNETR
ckpt_path: $@bundle_root + '/model_fold' + str(@fold)+'_lowerRes'
data_file_base_dir: /RW/2022/auto3dseg/btcv_testrun/82142
data_list_file_path: /RW/2022/auto3dseg/btcv_testrun/datafolds/BTCV_folds.json
determ: false
finetune:
  activate: false
  pretrained_ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'
fold: 0
infer:
  ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'
  data_list_key: testing
  fast: false
  ouptut_path: $@bundle_root + '/prediction_' + @infer#data_list_key
input_channels: 1
learning_rate: 0.0004
loss:
  _target_: DiceCELoss
  batch: true
  include_background: true
  sigmoid: $not @softmax
  smooth_dr: 1.0e-06
  smooth_nr: 0
  softmax: $@softmax
  squared_pred: true
  to_onehot_y: $@softmax
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  optimizer: $@optimizer
  step_size: $@num_iterations // 5
num_images_per_batch: 2
num_iterations: 10000
num_iterations_per_validation: 200
num_patches_per_image: 1
num_sw_batch_size: 1
optimizer:
  _target_: torch.optim.AdamW
  lr: '@learning_rate'
  weight_decay: 1.0e-05
output_classes: 14
overlap_ratio: 0.25
patch_size:
- 96
- 96
- 96
patch_size_valid:
- 96
- 96
- 96
softmax: true
validate:
  ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'
  ouptut_path: $@bundle_root + '/prediction_fold' + str(@fold)
  save_mask: true
