image_key: image
transforms_infer:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: '@image_key'
  - _target_: EnsureChannelFirstd
    keys: '@image_key'
  - _target_: Orientationd
    axcodes: RAS
    keys: '@image_key'
  - _target_: Spacingd
    align_corners: true
    keys: '@image_key'
    mode: bilinear
    pixdim:
    - 1.0
    - 1.0
    - 1.0
  - _target_: ScaleIntensityRanged
    a_max: 230
    a_min: 0.0
    b_max: 1.0
    b_min: 0.0
    clip: true
    keys: '@image_key'
  - _target_: CastToTyped
    dtype: $torch.float32
    keys: '@image_key'
