---
# hyper-parameters
amp: true
bundle_root: /RW/2022/auto3dseg/btcv_testrun/auto3dseg/monai/apps/auto3dseg/algo_teamplates/segresnet2d
ckpt_path: $@bundle_root + '/model_fold' + str(@fold)
data_file_base_dir: /RW/2022/auto3dseg/btcv_testrun/82142
data_list_file_path: /RW/2022/auto3dseg/btcv_testrun/datafolds/BTCV_folds.json

determ: false
fold: 0
input_channels: 1
learning_rate: 0.025
num_adjacent_slices: 1
num_images_per_batch: 3
num_iterations: 40000
num_iterations_per_validation: 500
num_patches_per_image: 1
num_sw_batch_size: 2
output_classes: 14
overlap_ratio: 0.25
patch_size: [-1, -1, "$@num_adjacent_slices * 2 + 1"]
patch_size_valid: [-1, -1, "$@num_adjacent_slices * 2 + 1"]
softmax: true

# training
loss:
  _target_: DiceFocalLoss
  include_background: true
  to_onehot_y: "$@softmax"
  softmax: "$@softmax"
  sigmoid: "$not @softmax"
  squared_pred: true
  batch: true
  smooth_nr: 1.0e-05
  smooth_dr: 1.0e-05
optimizer:
  _target_: torch.optim.SGD
  lr: "@learning_rate"
  momentum: 0.9
  weight_decay: 4.0e-05
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  optimizer: "$@optimizer"
  step_size: "$@num_iterations // 5"
  gamma: 0.5

# fine-tuning
finetune:
  activate: false
  pretrained_ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"

# validation
validate:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"
  save_mask: true
  ouptut_path: "$@bundle_root + '/prediction_fold' + str(@fold)"

# inference
infer:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"
  fast: false
  data_list_key: testing
  ouptut_path: "$@bundle_root + '/prediction_' + @infer#data_list_key"
