network:
  _target_: SegResNet
  act:
  - RELU
  - {inplace: false}
  dropout_prob: 0.1
  in_channels: $@input_channels * (2 * @num_adjacent_slices + 1)
  init_filters: 32
  out_channels: '@output_classes'
  spatial_dims: 2
