name: Task04_Hippocampus
task: segmentation

modality: MRI
datalist: ./datafolds/msd_task04_hippocampus_folds.json # list of files
dataroot: /data/Task04_Hippocampus # data location

multigpu: True

class_names: [val_acc_ant, val_acc_post]
