name: Task03_Liver
task: segmentation

modality: CT
datalist: ./datafolds/msd_task03_liver_folds.json # list of files
dataroot: /data/Task03_Liver # data location

multigpu: True

class_names: [val_acc_liver, val_acc_tumor]
