transforms_validate:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: ['@image_key', '@label_key']
  - _target_: EnsureChannelFirstd
    keys: ['@image_key', '@label_key']
  - _target_: Orientationd
    axcodes: RAS
    keys: ['@image_key', '@label_key']
  - _target_: EnsureTyped
    data_type: tensor
    keys: ['@image_key', '@label_key']
  - _target_: Spacingd
    align_corners: [true, true]
    keys: ['@image_key', '@label_key']
    mode: [bilinear, nearest]
    pixdim: 0.625
  - {_target_: NormalizeIntensityd, channel_wise: true, keys: '@image_key', nonzero: true}
