---
image_key: image
transforms_infer:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: "@image_key"
  - _target_: EnsureChannelFirstd
    keys: "@image_key"
  - _target_: Orientationd
    keys: "@image_key"
    axcodes: RAS
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - _target_: Spacingd
    align_corners:
    - true
    - true
    keys:
    - '@image_key'
    - '@label_key'
    mode:
    - bilinear
    - nearest
    pixdim:
    - 1.0
    - 1.0
    - 1.0
  - _target_: ScaleIntensityRanged
    a_max: 250
    a_min: -175
    b_max: 1.0
    b_min: 0.0
    clip: true
    keys: '@image_key'
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
