---
image_key: image
label_key: label
transforms_train:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: ["@image_key", "@label_key"]
  - _target_: EnsureChannelFirstd
    keys: ["@image_key", "@label_key"]
  - _target_: Orientationd
    keys: ["@image_key", "@label_key"]
    axcodes: RAS
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - _target_: Spacingd
    align_corners:
    - true
    - true
    keys:
    - '@image_key'
    - '@label_key'
    mode:
    - bilinear
    - nearest
    pixdim:
    - 1.5
    - 1.5
    - 2.0
  - _target_: ScaleIntensityRanged
    a_max: 250
    a_min: -175
    b_max: 1.0
    b_min: 0.0
    clip: true
    keys: '@image_key'
  - _target_: CastToTyped
    keys: ["@image_key", "@label_key"]
    dtype: ["$np.float16", "$np.uint8"]
  - _target_: EnsureTyped
    keys: ["@image_key", "@label_key"]
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - _target_: SpatialPadd
    keys: ["@image_key", "@label_key"]
    spatial_size: "@patch_size"
    mode: [reflect, constant]

  # data augmentation
  - _target_: RandCropByLabelClassesd
    keys: ["@image_key", "@label_key"]
    label_key: "@label_key"
    num_classes: "@output_classes"
    spatial_size: "@patch_size"
    num_samples: "@num_patches_per_image"
  - _target_: RandRotated
    keys: ["@image_key", "@label_key"]
    range_x: 0.3
    range_y: 0.3
    range_z: 0.3
    mode: [bilinear, nearest]
    prob: 0.2
  - _target_: RandZoomd
    keys: ["@image_key", "@label_key"]
    min_zoom: 0.8
    max_zoom: 1.2
    mode: [trilinear, nearest]
    prob: 0.16
  - _target_: RandGaussianSmoothd
    keys: "@image_key"
    sigma_x: [0.5, 1.15]
    sigma_y: [0.5, 1.15]
    sigma_z: [0.5, 1.15]
    prob: 0.15
  - _target_: RandScaleIntensityd
    keys: "@image_key"
    factors: 0.3
    prob: 0.5
  - _target_: RandShiftIntensityd
    keys: "@image_key"
    offsets: 0.1
    prob: 0.5
  - _target_: RandGaussianNoised
    keys: "@image_key"
    std: 0.01
    prob: 0.15
  - _target_: RandFlipd
    keys: ["@image_key", "@label_key"]
    spatial_axis: 0
    prob: 0.5
  - _target_: RandFlipd
    keys: ["@image_key", "@label_key"]
    spatial_axis: 1
    prob: 0.5
  - _target_: RandFlipd
    keys: ["@image_key", "@label_key"]
    spatial_axis: 2
    prob: 0.5
  - _target_: CastToTyped
    keys: ["@image_key", "@label_key"]
    dtype: ["$torch.float32", "$torch.uint8"]
